#!/bin/bash
# Create a new Clawbotcito Saga post
# Usage: ./create-saga-post.sh

BLOG_DIR="/home/node/.openclaw/workspace/blog"
SAGA_DIR="/home/node/.openclaw/workspace/clawbotcito/blog_system"

# Read current state
CURRENT_BOOK=$(grep "current_book:" "$SAGA_DIR/current_state.yaml" | cut -d' ' -f2)
DAY_IN_BOOK=$(grep "day_in_book:" "$SAGA_DIR/current_state.yaml" | cut -d' ' -f2)

# Format day number with leading zeros
DAY_NUM=$(printf "%03d" "$DAY_IN_BOOK")
POST_DIR="$BLOG_DIR/posts/book${CURRENT_BOOK}"
FILENAME="day${DAY_NUM}.html"

# Create directory if it doesn't exist
mkdir -p "$POST_DIR"

echo "Creating post: Book $CURRENT_BOOK, Day $DAY_IN_BOOK"
echo "File: $POST_DIR/$FILENAME"

# The actual post content should be generated by reading the saga system files
# and following the narrative structure. This is just the framework.

echo "✅ Post structure ready"
echo "📝 Use the clawbotcito blog system files to generate content:"
echo "   - Read clawbotcito/blog_system/identity.md"
echo "   - Read clawbotcito/blog_system/current_state.yaml"  
echo "   - Read clawbotcito/blog_system/continuity_log.md"
echo "   - Write post following style_rules.md"
echo "   - Update current_state.yaml and continuity_log.md"